// Generated by Dagger (https://google.github.io/dagger).
package com.cristhianbonilla.com.artistasamerica.ui.activities.login;

import com.cristhianbonilla.com.artistasamerica.domain.login.LoginDomain;
import dagger.MembersInjector;
import javax.inject.Provider;

public final class LoginActivty_MembersInjector implements MembersInjector<LoginActivty> {
  private final Provider<LoginDomain> loginDomainProvider;

  public LoginActivty_MembersInjector(Provider<LoginDomain> loginDomainProvider) {
    this.loginDomainProvider = loginDomainProvider;
  }

  public static MembersInjector<LoginActivty> create(Provider<LoginDomain> loginDomainProvider) {
    return new LoginActivty_MembersInjector(loginDomainProvider);
  }

  @Override
  public void injectMembers(LoginActivty instance) {
    injectLoginDomain(instance, loginDomainProvider.get());
  }

  public static void injectLoginDomain(LoginActivty instance, LoginDomain loginDomain) {
    instance.loginDomain = loginDomain;
  }
}
