// Generated by Dagger (https://google.github.io/dagger).
package com.cristhianbonilla.com.chilapp.ui.activities.Splash;

import com.cristhianbonilla.com.chilapp.domain.login.LoginDomain;
import dagger.MembersInjector;
import javax.inject.Provider;

public final class SplashActivity_MembersInjector implements MembersInjector<SplashActivity> {
  private final Provider<LoginDomain> loginDomainProvider;

  public SplashActivity_MembersInjector(Provider<LoginDomain> loginDomainProvider) {
    this.loginDomainProvider = loginDomainProvider;
  }

  public static MembersInjector<SplashActivity> create(Provider<LoginDomain> loginDomainProvider) {
    return new SplashActivity_MembersInjector(loginDomainProvider);
  }

  @Override
  public void injectMembers(SplashActivity instance) {
    injectLoginDomain(instance, loginDomainProvider.get());
  }

  public static void injectLoginDomain(SplashActivity instance, LoginDomain loginDomain) {
    instance.loginDomain = loginDomain;
  }
}
