// Generated by Dagger (https://google.github.io/dagger).
package com.cristhianbonilla.com.chilapp.ui.activities.register;

import com.cristhianbonilla.com.domain.repositories.login.repositories.features.login.LoginDomain;
import dagger.MembersInjector;
import javax.inject.Provider;

public final class RegisterActivity_MembersInjector implements MembersInjector<RegisterActivity> {
  private final Provider<LoginDomain> loginDomainProvider;

  public RegisterActivity_MembersInjector(Provider<LoginDomain> loginDomainProvider) {
    this.loginDomainProvider = loginDomainProvider;
  }

  public static MembersInjector<RegisterActivity> create(
      Provider<LoginDomain> loginDomainProvider) {
    return new RegisterActivity_MembersInjector(loginDomainProvider);
  }

  @Override
  public void injectMembers(RegisterActivity instance) {
    injectLoginDomain(instance, loginDomainProvider.get());
  }

  public static void injectLoginDomain(RegisterActivity instance, LoginDomain loginDomain) {
    instance.loginDomain = loginDomain;
  }
}
